# Site Metadata
title: "PeoPay Documentation"
description: >
  Official documentation for PeoPay, including white papers, strategic plans,
  and technical details.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman